= Robot basketball manager
:source-highlighter: highlightjs

https://github.com/ut-robotics/robot-basketball-rules[Competition rules]

== Referee's signals

Robots can connect to basketball manager software over Wi-Fi using WebSocket protocol.
Messages use JSON format.

=== Start

|===
|*Parameter* |*Type* |*Description*
|messageId |Integer |Unique ID for each message sent by server. Used by server to check ACK messages.
|signal |String constant |`start` for start signal.
|targets |String array |List of Robot IDs.
|baskets |String array |List of basket colors.
First item is the basket, in which the first target/robot should throw the balls.
Second item is the basket for the second robot and so on.
|===

*Examples*

Start signal.
First robot (`io`) should throw into `magenta` basket and second robot (`001trt`) into `blue` basket.
[source,json]
----
{
  "messageId": 1,
  "signal": "start",
  "targets":  ["io", "001trt"],
  "baskets": ["magenta", "blue"]
}
----

=== Stop and ping

|===
|*Parameter* |*Type* |*Description*
|messageId |Integer |Unique ID for each message sent by server. Used by server to check ACK messages.
|signal |String constant |`stop` for stop signal. `ping` for ping signal.
|targets |String array |List of Robot IDs.
|===

*Examples*

Stop signal for robots with IDs of `io` and `001trt`.
[source,json]
----
{
  "messageId": 1,
  "signal": "stop",
  "targets": ["io", "001trt"]
}
----

=== ACK responses

Robot must send ACK (acknowledgement) to server
when `targets` array contains the robot's ID or `*` (asterisk, U+002A).

|===
|*Parameter* |*Type* |*Description*
|type |String constant |`ack` for all ACK messages.
|data |String |Unmodified received message.
|===

*Examples*

. Server sends stop signal for robots with IDs of `io` and `001trt`.
+
[source,json]
----
{"messageId":1,"signal":"stop","targets":["io", "001trt"]}
----
+
Robots with IDs of `io` and `001trt` send ACK to server.
+
[source,json]
----
{
  "type": "ack",
  "data": {"messageId":1,"signal":"stop","targets":["io","001trt"]}
}
----

. Server sends ping signal to all robots.
+
[source,json]
----
{"messageId":2,"signal":"ping","targets":["*"]}
----
+
Robots send ACK to server.
+
[source,json]
----
{
  "type": "ack",
  "data": {"messageId":2,"signal":"ping","targets":["*"]}
}
----

== Swiss-system tournament

=== Game point system

|===
|Round results |Winner points |Loser points

|2 out of 2 wins |10 |0
|2 wins and 1 tie |9 |1
|2 wins and 1 loss |8 |2
|1 win and 2 ties |7 |3
|3 ties or 1 win, 1 loss, 1 tie |5 |5
|===

=== Byes

With odd number of robots, a robot is chosen randomly that skips a round of Swiss-system tournament games.
Robot is not chosen more than once.
No points are rewarded for that robot.

=== Scoreboard

Robots are ranked by average game score.
Robot with the highest average score ranks the highest.

If the average scores are equal, the tiebreak scores are used.
Robot's tiebreak score is calculated by summing the average scores
of all the opponent robots that the robot has played against.
Robot with higher tiebreak score ranks higher.
Higher tiebreak scores indicates that the robot has played against stronger opponents.

== Double elimination tournament

Four (or more if there are ties) Swiss-system tournament robots are matched based on the ranking
so that the best robot matches with the worst robot.
In case of four robots the matching is 1-4, 2-3.
I case of five robots it is 1-5, 2-4.
3rd place will be matched with the winner of the match between 1st and 5th place robots.

== Setup

. Install https://nodejs.org/en/[node.js]

. Install dependencies
+
In `server` directory run `npm i`.

== Usage

=== Manual command server

. In `server` directory run `node manual-command-server.mjs`.

. In robot's code create WebSocket client that connects to
** `localhost:8111`, if the server and robot's code is on the same computer;
** `<server computer IP address>:8111`, if the server and robot's code are on different computers.
Make sure that server and robot are in the same network.
** Basic authentication must be used with robot's ID and empty password when connecting to server.
*** URL format: `ws://<robot's ID>:@<server computer IP address>:8111`
*** Examples:
**** `ws://io:@localhost:8111`
**** `ws://001trt:@192.168.0.1:8111`
. Open `localhost:8220` or `<server computer IP address>:8220` in the web browser to send signals.
